In [17]:
# Copyright 2019 Chao Wang
# Licensed under the MIT License (the "License").
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at https://mit-license.org

# Feburary 2019
# This script tests the function from sharpen.py.

# This script tests sharpen function of filterizePy package.
# This function sharpens an image.
# Input  : An image in .png, .jpeg,.gif,.bmp, .jpg format
# Output : A sharpened image in the same format as the input image file type

import numpy as np
import pandas as pd
import os
import imghdr
import skimage.io
from PIL import Image
from filterizePy import sharpen

ModuleNotFoundError: No module named 'filterizePy'

In [19]:
def sharpen(input_img)
    """This function sharpens an image.
    
    This function takes the input image of its size and ouput a sharpened image through the sharpen convolution filter.
    read from the image path
    apply filter
    save the output image to the same folder, call the image transformed.
    
    Parameters
    ----------
    input_img: an image file from file path
    
    Returns
    -------
    output_img: an image file
        This is the sharpened image, it has the same dimension and file type as the input_img
    Example
    -------
    """
    
    img = preprocess_image(input_img)
    ft = np.zeros((3,3))
    ft[1,1] = 5
    ft[0,1]=ft[1,0]=ft[1,2]=ft[2,1]=-2
    print(ft)
    res = show_conv(img, ft)
    return output_img

SyntaxError: invalid syntax (<ipython-input-19-535074a6253a>, line 1)

In [18]:
def check_input_type():
    """ This function checks the input image
    """
    assert imghdr.what(input_img) in ['png','jpeg','gif','bmp','jpg'] 
    
def check_output_type():
    assert imghdr.what(output_img) in ['png','jpeg','gif','bmp','jpg'] and 
    imghdr.what(output_img)==imghdr.what(input_img)
    

def check_output_dimension(input_img, output_img):
    in_width, in_height = input_img.size
    out_width, out_height = output_img.size
    assert in_with == out_width and in_height==out_height
    
def check_input_path():
    
def check_output_path():

def

SyntaxError: invalid syntax (<ipython-input-18-70409854680c>, line 1)

reference: https://docs.python.org/2/library/imghdr.html

In [21]:
ft = np.zeros((3,3))
ft[1,1] = 5
ft[0,1]=ft[1,0]=ft[1,2]=ft[2,1]=-2
print(ft)

[[ 0. -2.  0.]
 [-2.  5. -2.]
 [ 0. -2.  0.]]
